# This is a basic workflow to help you get started with Actions

name: Send mail
# Controls when the workflow will run
on:
	# Triggers the workflow on push
	push:
jobs:
	email:
		runs-on: ubuntu-latest
		steps:
      name: Homeless project
      uses: dawidd6/action-send-mail@v3
      with:
        subject: New file pushed to the repository
        body: A new file has been pushed to the repository
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        to: roliyaml@gmail.com
        from: Roli Github Test
